image: jonatkinson/python-poetry:3.7

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PRE_COMMIT_VERSION: "1.15.1"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


before_script:
    # gitlab cannot pickup absolute path, hence use a local virtualenv
  - poetry config settings.virtualenvs.in-project true

stages:
  - check
  - build
  - test
  - deploy

check:
  stage: check
  before_script:
    - pip install pre-commit==$PRE_COMMIT_VERSION
  script:
    - make check

build-python:
  stage: build
  cache:
      key: ${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}
      paths:
      - .cache/pip
      - .venv/
  artifacts:
    expire_in: 1 hour
    paths:
      - .venv/
  script:
    - poetry install

unit-test:
  stage: test
  dependencies:
  - build-python
  script:
    - make unit-test

release:
  stage: deploy
  when: manual
  script:
    - poetry install
    - poetry run reliesl release --pypi-release testpypi

